### ISSUE TITLE
How do I use this plugin?

### ISSUE THREAD

**Issue by RdeWilde** [gbksoft/yii2-swagger#1]
Do I have to put it in my routes? Or open a specific URL?

@littlefuntik @Dell- @golcinho @gbksoftuser

**Comment by Dell-** [comment]
Hi,
This module uses standard rules of Yii2 routing.
Add this module into your config file of application.
Use standard path - <module-name>/<controller-name>/<action-name>
see >> https://github.com/gbksoft/yii2-swagger/blob/master/controllers/DefaultController.php

But this module have specific code for our company.

My recommendation - use original UI app as separate app
Swagger UI -> https://github.com/swagger-api/swagger-ui

Sorry for my bad english

**Comment by RdeWilde** [comment]
Ah, thanks for the fast response. So this module does not generate the swagger json file/specs, but reads this?

**Comment by Dell-** [comment]
Yes, only read swagger.json for build UI as http://petstore.swagger.io/

**Comment by RdeWilde** [comment]
Thanks
